### PR TITLE
Pretty print env

### PR DESCRIPTION
**Pull request by kitemongerer**

### CODE REVIEW

**Review by josephgee — APPROVED** [review]
@kitemongerer Yeah, I wanted to do that, thanks!

**Comment by trevorwhitney** [comment]
This merge broke our pipelines... it doesn't look like `sh` has a `-o pipefail` option? Can we use `bash` instead, or remove this option?

**Comment by trevorwhitney** [comment]
so removing the pipefail didn't work either... we had to revert the merge to unblock our pipelines

**Comment by trevorwhitney** [comment]
My bad... it's back :)

**Pull request merged**
